matrix:
  core:
    parameter: core
  python:
    parameter: python
  libraries:
    parameter: libraries
  blink_planner:
    parameter: blink_planner
  connectors:
    parameter: connectors
  kafka_gelly:
    parameter: kafka/gelly
  tests:
    parameter: tests
  scheduler_ng_core:
    parameter: scheduler_ng_core
  scheduler_ng_tests:
    parameter: scheduler_ng_tests
  misc:
    parameter: misc